server {
    listen 80;
    server_name wwffsq.space www.wwffsq.space;

    root /var/www/imsit_shop;
    index index.php;

    charset utf-8;
    client_max_body_size 10M;

    # закрываем доступ к includes
    location ~ ^/includes/ {
        deny all;
        return 403;
    }

    # статика (фото товаров)
    location /uploads/ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # все запросы
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # обработка PHP через php-fpm
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # запрещаем доступ к скрытым файлам
    location ~ /\. {
        deny all;
    }
}